-------------------------------------------------------------------------------
Test set: curso.generation.demo.DemoBootApplicationTests
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 168.046 s <<< FAILURE! - in curso.generation.demo.DemoBootApplicationTests
test2  Time elapsed: 23.573 s  <<< ERROR!
org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at curso.generation.demo.DemoBootApplicationTests.test2(DemoBootApplicationTests.java:34)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at curso.generation.demo.DemoBootApplicationTests.test2(DemoBootApplicationTests.java:34)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at curso.generation.demo.DemoBootApplicationTests.test2(DemoBootApplicationTests.java:34)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at curso.generation.demo.DemoBootApplicationTests.test2(DemoBootApplicationTests.java:34)
Caused by: java.net.ConnectException: Connection timed out: connect
	at curso.generation.demo.DemoBootApplicationTests.test2(DemoBootApplicationTests.java:34)

contextLoads  Time elapsed: 22.33 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at curso.generation.demo.DemoBootApplicationTests.contextLoads(DemoBootApplicationTests.java:27)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at curso.generation.demo.DemoBootApplicationTests.contextLoads(DemoBootApplicationTests.java:27)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at curso.generation.demo.DemoBootApplicationTests.contextLoads(DemoBootApplicationTests.java:27)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: 
Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at curso.generation.demo.DemoBootApplicationTests.contextLoads(DemoBootApplicationTests.java:27)
Caused by: java.net.ConnectException: Connection timed out: connect
	at curso.generation.demo.DemoBootApplicationTests.contextLoads(DemoBootApplicationTests.java:27)

